import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="place-content-center flex justify-center items-center bg-slate-500">header</h1>
        {children}
        <h1 className="place-content-center flex justify-center items-center bg-slate-500">footer</h1>
        </body>
    </html>
  );
}
